name: Deploy lamda function

on:
  push:
    branches:
     - main
     
     
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/python@v2
        with:
          python-version: 3.8
      - name: install the libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt]; then pip install -r requirements.txt -t .; fi
      - name: create zip bundle
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: archieve artifact 
        uses: action/upload-artifact@v2
        with:
            name: zipped bundle
            path: ${{ github.sha }}.zip
            
     
       
